# Generated by Django 2.2.6 on 2019-11-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_designation',
            field=models.CharField(choices=[('Undergrad', 'Undergrad'), ('Grad Student', 'Grad Student'), ('Alumni', 'Alumni'), ('Not a student', 'Not a student')], default='None', max_length=20),
        ),
    ]
