# Generated by Django 2.2.6 on 2019-11-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191128_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_designation',
            field=models.CharField(blank=True, choices=[('Undergrad', 'Undergrad'), ('Grad Student', 'Grad Student'), ('Alumni', 'Alumni'), ('Not a student', 'Not a student')], default='None', max_length=20, null=True),
        ),
    ]
