# Generated by Django 2.2.6 on 2019-10-24 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='boards.Board')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('address', models.CharField(default='', max_length=200)),
                ('move_in_condition', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=5)),
                ('length_of_stay', models.CharField(choices=[('less than 6 months', 'less than 6 months'), ('6 months', '6 months'), ('10 months', '10 months'), ('12 months', '12 months'), ('More than 1 year', 'More than 1 year')], max_length=20)),
                ('treatment', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='3', max_length=5)),
                ('response_speed', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='3', max_length=5)),
                ('maintenance_quality', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='3', max_length=5)),
                ('security_return', models.CharField(choices=[('100%', '100%'), ('75%', '75%'), ('50%', '50%'), ('25%', '25%'), ('0%', '0%'), ('Still waiting', 'Still waiting')], default='1', max_length=5)),
                ('fair', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='1', max_length=5)),
                ('recommend', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='1', max_length=5)),
                ('additional_comments', models.TextField(max_length=4000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='boards.Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
