# Generated by Django 2.2.6 on 2019-10-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='fair',
            new_name='is_this_a_fair_amount',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='security_return',
            new_name='security_deposit_returned',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='address',
            new_name='unit_address',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='recommend',
            new_name='would_you_recommend',
        ),
        migrations.AlterField(
            model_name='review',
            name='maintenance_quality',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='move_in_condition',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='response_speed',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='treatment',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=5),
        ),
    ]
