# Generated by Django 2.2.6 on 2019-11-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20191027_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
