# Generated by Django 2.2.6 on 2019-11-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_company_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='length_of_stay',
            field=models.CharField(choices=[('less than 6 months', 'less than 6 months'), ('6 months', '6 months'), ('10 months', '10 months'), ('12 months', '12 months'), ('More than 1 year', 'More than 1 year')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='maintenance_quality',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='move_in_condition',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='response_speed',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='security_deposit_returned',
            field=models.CharField(choices=[('100%', '100%'), ('75%', '75%'), ('50%', '50%'), ('25%', '25%'), ('0%', '0%'), ('Still waiting', 'Still waiting')], default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='treatment',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=5),
        ),
    ]
