# Generated by Django 3.0 on 2019-12-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20191125_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='security_deposit_returned',
            field=models.CharField(choices=[('100%', '100%'), ('75%', '75%'), ('50%', '50%'), ('25%', '25%'), ('0%', '0%'), ('Still waiting', 'Still waiting')], default='None', max_length=13),
        ),
    ]
